spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 5000
    #password: